name: Deploy IPTV Worker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Wrangler
        run: npm install -g wrangler

      - name: Deploy Worker
        run: |
          wrangler deploy \
          --var HOST:${{ http://4k.spicetv.cc/stalker_portal/ }} \
          --var MAC:${{ 00:1A:79:00:2C:D8 }} \
          --var SERIAL:${{ 61A63207AA03F}} \
          --var DEVICE1:${{ 061A842DFD8AA25AA9184BAB968565D2E8831804C89956DA707F8396F7D4BBDB }} \
          --var DEVICE2:${{ 061A842DFD8AA25AA9184BAB968565D2E8831804C89956DA707F8396F7D4BBDB }}
        env:
          CLOUDFLARE_API_TOKEN: ${{cfut_5Ky25xecppg4hCr7YvisrSM0IATsI7MlFtJgeT9k374a788b }}
          CLOUDFLARE_ACCOUNT_ID: ${{ 319df34817fc10295b4eeabb4a5f4e8d }}
